### DSA-WEB-RESTService Configuration
server.port=8096
server.servlet.context-path=/DSA-WEB-RESTService/rest

### Conectarea la Spark SQL (Portul 10000 deschis de SparkSQLService)
spring.datasource.url=jdbc:hive2://localhost:10000
spring.datasource.driver-class-name=org.apache.hive.jdbc.HiveDriver
spring.datasource.username=hive
spring.datasource.password=

### Hibernate trebuie să folosească MySQLDialect pentru a fi compatibil cu Spark SQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Securitate pentru acest serviciu
spring.security.user.name=developer
spring.security.user.password=iis